"""
Phase 4 - Task 4.2: Train Student model on CoT dataset.
Fine-tunes Qwen3.5-0.8B using the CoT dataset generated by the teacher model.
Reuses the same Unsloth + SFTTrainer pipeline from Phase 2.
"""
import os
import sys
import argparse
from pathlib import Path
from datasets import load_dataset

# Fix Windows/Triton Compatibility Issue for Unsloth
os.environ["TORCHDYNAMO_DISABLE"] = "1"

# Add project root to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from src.config import settings
from src.models.trainer import setup_unsloth_model, create_trainer


def main():
    parser = argparse.ArgumentParser(description="Train Student on CoT dataset (Phase 4)")
    parser.add_argument("--data", type=str, default=None,
                        help=f"CoT dataset path (default: {settings.distillation.output_file})")
    parser.add_argument("--output-dir", type=str, default="outputs/models/cot-qwen3.5-0.8b",
                        help="Output directory for the trained model")
    parser.add_argument("--max-steps", type=int, default=None,
                        help="Limit training steps (for dry-run/debug)")
    parser.add_argument("--epochs", type=int, default=3,
                        help="Number of training epochs (default: 3)")
    parser.add_argument("--lr", type=float, default=2e-4,
                        help="Learning rate (default: 2e-4)")
    args = parser.parse_args()

    data_path = args.data or settings.distillation.output_file
    output_dir = args.output_dir

    print("=" * 60)
    print("Phase 4 - Task 4.2: Train Student on CoT Dataset (Unsloth)")
    print("=" * 60)

    # 1. Load CoT Dataset
    if not Path(data_path).exists():
        print(f"Error: CoT dataset not found at {data_path}.")
        print("Please run 05_generate_cot.py first.")
        sys.exit(1)

    print(f"\n[1/5] Loading CoT dataset from {data_path}...")
    dataset = load_dataset("json", data_files=data_path, split="train")
    print(f"  Samples: {len(dataset)}")

    # 2. Setup Unsloth Model & Tokenizer (same base model)
    print(f"\n[2/5] Loading base model: {settings.base.model_id}")
    model, tokenizer = setup_unsloth_model(
        model_name=settings.base.model_id,
        max_seq_length=settings.base.max_seq_len,
        lora_r=settings.base.lora_r,
        lora_alpha=settings.base.lora_alpha,
        target_modules=settings.base.target_modules,
        lora_dropout=settings.base.lora_dropout,
    )

    # 3. Training Parameters
    print(f"\n[3/5] Configuring training parameters...")
    training_args = {
        "per_device_train_batch_size": settings.base.per_device_train_batch_size,
        "gradient_accumulation_steps": settings.base.gradient_accumulation_steps,
        "warmup_ratio": settings.base.warmup_ratio,
        "num_train_epochs": args.epochs,
        "learning_rate": args.lr,
        "logging_steps": 10,
        "optim": settings.base.optim,
        "lr_scheduler_type": "cosine",
        "save_steps": 200,
    }

    if args.max_steps:
        print(f"  [DEBUG] Limiting to {args.max_steps} steps.")
        training_args["max_steps"] = args.max_steps

    print(f"  Epochs         : {args.epochs}")
    print(f"  Learning Rate  : {args.lr}")
    print(f"  Batch Size     : {training_args['per_device_train_batch_size']}")
    print(f"  Grad Accum     : {training_args['gradient_accumulation_steps']}")
    print(f"  Output Dir     : {output_dir}")

    # 4. Initialize Trainer
    print(f"\n[4/5] Initializing SFTTrainer...")
    trainer = create_trainer(
        model=model,
        tokenizer=tokenizer,
        dataset=dataset,
        max_seq_length=settings.base.max_seq_len,
        output_dir=output_dir,
        training_args=training_args,
    )

    # 5. Start Training
    print(f"\n[5/5] Starting training on {len(dataset)} CoT samples...")
    trainer_stats = trainer.train()

    # 6. Save Model
    print("\nTraining complete. Saving model...")
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"Model saved to: {output_dir}")

    # Stats
    print("\n" + "=" * 60)
    print("Training Summary")
    print("=" * 60)
    print(f"  Runtime       : {trainer_stats.metrics['train_runtime']:.1f}s")
    print(f"  Samples/sec   : {trainer_stats.metrics['train_samples_per_second']:.2f}")
    print(f"  Avg Loss      : {trainer_stats.metrics['train_loss']:.4f}")
    print(f"  Model Dir     : {output_dir}")
    print("=" * 60)


if __name__ == "__main__":
    main()
